// Code generated by mockery v1.1.2. DO NOT EDIT.

package mocks

import (
	data "authserver/data"

	mock "github.com/stretchr/testify/mock"
)

// DataAdapter is an autogenerated mock type for the DataAdapter type
type DataAdapter struct {
	mock.Mock
}

// CleanUp provides a mock function with given fields:
func (_m *DataAdapter) CleanUp() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateTransaction provides a mock function with given fields:
func (_m *DataAdapter) CreateTransaction() (data.Transaction, error) {
	ret := _m.Called()

	var r0 data.Transaction
	if rf, ok := ret.Get(0).(func() data.Transaction); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(data.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Setup provides a mock function with given fields:
func (_m *DataAdapter) Setup() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
