// Code generated by mockery v1.1.2. DO NOT EDIT.

package mocks

import (
	data "github.com/mhogar/amber/data"

	mock "github.com/stretchr/testify/mock"
)

// DataAdapter is an autogenerated mock type for the DataAdapter type
type DataAdapter struct {
	mock.Mock
}

// CleanUp provides a mock function with given fields:
func (_m *DataAdapter) CleanUp() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetExecutor provides a mock function with given fields:
func (_m *DataAdapter) GetExecutor() data.DataExecutor {
	ret := _m.Called()

	var r0 data.DataExecutor
	if rf, ok := ret.Get(0).(func() data.DataExecutor); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(data.DataExecutor)
		}
	}

	return r0
}

// Setup provides a mock function with given fields:
func (_m *DataAdapter) Setup() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
