// Code generated by mockery v1.1.2. DO NOT EDIT.

package mocks

import (
	data "authserver/data"

	migrationrunner "github.com/mhogar/migrationrunner"
	mock "github.com/stretchr/testify/mock"
)

// MigrationRepositoryFactory is an autogenerated mock type for the MigrationRepositoryFactory type
type MigrationRepositoryFactory struct {
	mock.Mock
}

// CreateMigrationRepository provides a mock function with given fields: _a0
func (_m *MigrationRepositoryFactory) CreateMigrationRepository(_a0 data.DataExecutor) migrationrunner.MigrationRepository {
	ret := _m.Called(_a0)

	var r0 migrationrunner.MigrationRepository
	if rf, ok := ret.Get(0).(func(data.DataExecutor) migrationrunner.MigrationRepository); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(migrationrunner.MigrationRepository)
		}
	}

	return r0
}
