// Code generated by mockery v1.1.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Renderer is an autogenerated mock type for the Renderer type
type Renderer struct {
	mock.Mock
}

// RenderView provides a mock function with given fields: name, data
func (_m *Renderer) RenderView(name string, data interface{}) []byte {
	ret := _m.Called(name, data)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(string, interface{}) []byte); ok {
		r0 = rf(name, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}
