language: go
os: linux
dist: bionic
env:
  - GO111MODULE=on CFG_ENV=travis COVERALLS_PARALLEL=true
go:
  - 1.14.x
notifications:
  webhooks: https://coveralls.io/webhook

jobs:
  include:
    - stage: Build And Unit Tests
      name: AuthServer
      install:
        - go get github.com/mattn/goveralls
      script: 
        - go build
        - go test ./controllers/ ./models/ ./helpers/ ./router/ -v -covermode=count -coverprofile=coverage.out
        - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci
    - name: MigrationRunner
      before_install:
        - cd database/migration_runner
      install:
        - go get github.com/mattn/goveralls
      script:
        - go build
        - go test -v -covermode=count -coverprofile=coverage.out
        - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci
    - stage: Integration Tests
      name: Postgres Integration Tests
      services:
        - postgresql
      install:
        - go get github.com/mattn/goveralls
      before_script:
        - psql -c 'create database travis_ci_test;' -U postgres
        - go run database/migration_runner/main.go -db=integration
      script:
        - go test ./database/sql_adapter/ -v -covermode=count -coverprofile=coverage.out
        - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci
