language: go
os: linux
dist: bionic
env:
  - GO111MODULE=on CFG_ENV=travis COVERALLS_PARALLEL=true
go:
  - 1.14.x
notifications:
  webhooks: https://coveralls.io/webhook

jobs:
  include:
    - stage: Build
      name: Build AuthServer
      install: skip
      script: 
        - go build
    - stage: Test
      name: AuthServer Unit Tests
      install:
        - go get github.com/mattn/goveralls
      script:
        - go test ./controllers/ ./models/ ./helpers/ ./router/ -v -covermode=count -coverprofile=coverage.out
        - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci
      - name: Database Integration Tests
      services:
        - postgresql
      install:
        - go get github.com/mattn/goveralls
      before_script:
        - psql -c 'create database travis_ci_test;' -U postgres
      script:
        - go test ./database/sql_adapter/ -v -covermode=count -coverprofile=coverage.out
        - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci
