app_name: Test App
token:
    default_issuer: "test"
    lifetime: 60
permissions:
    min_client_rank: 5
database:
    connection_strings:
        core: ""
        integration: postgres://postgres:password@localhost:5432/ci_test?sslmode=disable
    timeout: 5000
password_criteria:
    min_length: 8
    require_lower_case: true
    require_upper_case: true
    require_digit: true
    require_symbol: true
