// Code generated by mockery v1.1.2. DO NOT EDIT.

package mocks

import (
	data "github.com/mhogar/amber/data"
	runner "github.com/mhogar/amber/tools/migration_runner/runner"

	mock "github.com/stretchr/testify/mock"
)

// MigrationRunnerFactory is an autogenerated mock type for the MigrationRunnerFactory type
type MigrationRunnerFactory struct {
	mock.Mock
}

// CreateMigrationRunner provides a mock function with given fields: _a0
func (_m *MigrationRunnerFactory) CreateMigrationRunner(_a0 data.DataExecutor) runner.MigrationRunner {
	ret := _m.Called(_a0)

	var r0 runner.MigrationRunner
	if rf, ok := ret.Get(0).(func(data.DataExecutor) runner.MigrationRunner); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(runner.MigrationRunner)
		}
	}

	return r0
}
