// Code generated by mockery v1.1.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RawDataLoader is an autogenerated mock type for the RawDataLoader type
type RawDataLoader struct {
	mock.Mock
}

// Load provides a mock function with given fields: uri
func (_m *RawDataLoader) Load(uri string) ([]byte, error) {
	ret := _m.Called(uri)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(uri)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(uri)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
