// Code generated by mockery v1.1.2. DO NOT EDIT.

package mocks

import (
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// TokenFactory is an autogenerated mock type for the TokenFactory type
type TokenFactory struct {
	mock.Mock
}

// CreateToken provides a mock function with given fields: keyUri, clientUID, username
func (_m *TokenFactory) CreateToken(keyUri string, clientUID uuid.UUID, username string) (string, error) {
	ret := _m.Called(keyUri, clientUID, username)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, uuid.UUID, string) string); ok {
		r0 = rf(keyUri, clientUID, username)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, uuid.UUID, string) error); ok {
		r1 = rf(keyUri, clientUID, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
