// Code generated by mockery v1.1.2. DO NOT EDIT.

package mocks

import (
	jwthelpers "authserver/controllers/jwt_helpers"

	mock "github.com/stretchr/testify/mock"
)

// TokenFactorySelector is an autogenerated mock type for the TokenFactorySelector type
type TokenFactorySelector struct {
	mock.Mock
}

// Select provides a mock function with given fields: tokenType
func (_m *TokenFactorySelector) Select(tokenType int) jwthelpers.TokenFactory {
	ret := _m.Called(tokenType)

	var r0 jwthelpers.TokenFactory
	if rf, ok := ret.Get(0).(func(int) jwthelpers.TokenFactory); ok {
		r0 = rf(tokenType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jwthelpers.TokenFactory)
		}
	}

	return r0
}
