// Code generated by mockery v1.1.2. DO NOT EDIT.

package mocks

import (
	data "authserver/data"
	interfaces "authserver/tools/migration_runner/interfaces"

	mock "github.com/stretchr/testify/mock"
)

// IMigrationRunnerFactory is an autogenerated mock type for the IMigrationRunnerFactory type
type IMigrationRunnerFactory struct {
	mock.Mock
}

// CreateMigrationRunner provides a mock function with given fields: _a0
func (_m *IMigrationRunnerFactory) CreateMigrationRunner(_a0 data.DataExecutor) interfaces.MigrationRunner {
	ret := _m.Called(_a0)

	var r0 interfaces.MigrationRunner
	if rf, ok := ret.Get(0).(func(data.DataExecutor) interfaces.MigrationRunner); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.MigrationRunner)
		}
	}

	return r0
}
