// Code generated by mockery v1.1.2. DO NOT EDIT.

package mocks

import (
	data "authserver/data"

	mock "github.com/stretchr/testify/mock"
)

// IMigrationRunnerFactory is an autogenerated mock type for the IMigrationRunnerFactory type
type IMigrationRunnerFactory struct {
	mock.Mock
}

// CreateMigrationRunner provides a mock function with given fields: exec
func (_m *IMigrationRunnerFactory) CreateMigrationRunner(exec data.DataExecutor) MigrationRunner {
	ret := _m.Called(exec)

	var r0 MigrationRunner
	if rf, ok := ret.Get(0).(func(data.DataExecutor) MigrationRunner); ok {
		r0 = rf(exec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(MigrationRunner)
		}
	}

	return r0
}
