name: CI
on: [push, pull_request]
env:
  CFG_ENV: test
jobs:
  build:
    name: Build and Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...
    
    - name: Unit Tests
      run: go test -v -race -covermode=atomic -coverprofile=coverage.out ./controllers/ ./controllers/password_helpers/ ./data/ ./models/ ./router/ ./router/handlers/ ./server/ ./tools/admin_creator/ ./tools/migration_runner/

    - name: Install Goveralls
      run: go install github.com/mattn/goveralls@latest

    - name: Send Coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: goveralls -coverprofile=coverage.out -service=github
