name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build and Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...
    
    - name: Unit Tests
      run: go test -v ./controllers/ ./controllers/password_helpers/ ./data/ ./models/ ./router/ ./router/handlers/ ./server/ ./tools/admin_creator/ ./tools/migration_runner/    
